### ISSUE TITLE
Suggestion: Create a demo for users to try/see working Chartmoji

### ISSUE THREAD

**Issue by riordan** [threatsimple/chartmoji#1]
I'd love to use Chartmoji, but before I install it on my org's massive slack instance, I want to know what the payoff will be. Having a working Slack to see it in action on would be great.  Heck even just a GIF of the different chart types being typed, then how they play out.

**Comment by nod** [comment]
Hi!  This is a great idea. Thanks for speaking up.

I've created an open slack team called `chartmoji`.   The chartmojis are currently uploading.

Here's an invite link that should never expire:

https://join.slack.com/t/chartmoji/shared_invite/enQtODg1NDg3MDgyMTk3LTM5ZjA2MTI3NWVmNzI1Y2M1MTRjMjcwYWEyNTUxZGRlZDMyNzBlOWQ3YzI0ZGIwNmFiNTBiNTUwMzc4ZDc2YTE

I'll also add it to the README.
